apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: dogood-pipeline
serialPipeline:
  stages:
    - targetId: gke-prod

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gke-prod
gke:
  cluster: projects/dogood-488720/locations/us-central1/clusters/dogood-cluster
