apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dogood-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "dogood-cert"
spec:
  rules:
    - host: api.wedogood.help
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dogood-service
                port:
                  number: 80
